[[MQLib]]
arch = "aarch64"
git-tree-sha1 = "57a5f1729c6906e8c337eca3ddf9dba15eeba46c"
os = "macos"

    [[MQLib.download]]
    sha256 = "5e84127da84a9259ce0f6af9a187db179e539de63e6ac50a2ceb29dba055b8ae"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.aarch64-apple-darwin.tar.gz"
[[MQLib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b4833e7121fc5c7e567486d7011c014da7c279d"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "2f960e92ace81c42d3e6723ad4e824d9f452127d31a41b8e25025aa8eac3e505"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4491b1cffd66eaf6f61d40b0c36cde593e1e12e7"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "983a487e1be902bd1d8aab28a85c6d6a543c274b5d31f9d863d943c2b85596f8"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[MQLib]]
arch = "aarch64"
git-tree-sha1 = "6783f242584ff59d03d477558964ecc3359b61b4"
os = "freebsd"

    [[MQLib.download]]
    sha256 = "8b8adada931fba9f8ab4dfbc1f8af5df540697e53efffbc3441333e5c419aff8"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.aarch64-unknown-freebsd.tar.gz"
[[MQLib]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18592648ddb8cc928720ebb2009c361600e9670f"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "1765dc7396b687d89cbb5a8d90095ff84800cf38960dcb0a516026a9e48d8494"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MQLib]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30fb7248f55fbfc8471024fe0208b695348676d8"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "6ca4640582b3ec35c40da399c152d0297a550e892be17ab2a2787e00e43462e1"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MQLib]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e2b00d6312ca76275617e8fcb63bdd5bec44bcf"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "bdb4c2572579be7d3bb84ae796dfa294ccae552979ad09e1a67ddaa51da97598"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MQLib]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73622702f3f54133b7d085cbaa35c4037864b495"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "5997ed2a942b01e23d4c9210378509e61b1f0ec5627abde0c13775ebe407f312"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MQLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0109679f345980a9719897c7bd95901966673e5e"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "2e3199f07a6b2845df043ec1d46a5da527a7c6ffd5f2a6129f01aa46c4e03a79"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.i686-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5fe34281049bd1f8ff3b437ad8677c695638e5c"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "4934ab0e0528565f48bb6e3b0e4fa964483bb440685f1d4d7b07b2e180e6fe01"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.i686-linux-musl-cxx11.tar.gz"
[[MQLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ea9629ddef5ede8bf14ec35cc6dcd780deb5559"
os = "windows"

    [[MQLib.download]]
    sha256 = "fb30990dfc6581ec47ed91871539d9ea9f7a222d7072fc69c8387cc169b27aa2"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.i686-w64-mingw32-cxx11.tar.gz"
[[MQLib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca28309ba3f9eba2e6ed275ac8014debd178ae93"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "7b786ec6d1a0f969f54e2db82180fe52dbda59d554603e630c2be031b92b8ae3"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5323aea814a571cb37cb88e714ef6e524e691836"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "0fdf5bb210d0bd21b8acf4b3dc2e22d9ff9578c0aa05899c47230789acdc7f09"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.riscv64-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "x86_64"
git-tree-sha1 = "5c890c56162a50fe3f4eb17e33bdc87d78affecf"
os = "macos"

    [[MQLib.download]]
    sha256 = "a93f0a416208e18efae5546e710532a965f9696da76b6e01c0c00b6fcfb9aee0"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.x86_64-apple-darwin.tar.gz"
[[MQLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db96ac0a86c22965921940edd879a28eab6d8d70"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "91ea27e609828d9656b8cf4c21c463b5799dfb9f46740d21d82f9c60bb9b81df"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d59ca1ddf71320b7ccb4f9675ff22099df60661"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "f2f955a6adee7c4b643b922bd2d52a50b800c97830193b1088a40baf649d7b7a"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[MQLib]]
arch = "x86_64"
git-tree-sha1 = "00a679600fa6fe069c29b4c9bc5bcaf81b19ca1e"
os = "freebsd"

    [[MQLib.download]]
    sha256 = "9631f255f3361f63c09f4b29ba7b393f078cc190df47022e3e4ecf5b5fb94699"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.x86_64-unknown-freebsd.tar.gz"
[[MQLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2864e1abf8789f19a35e053a9ad0c313ceb4f46b"
os = "windows"

    [[MQLib.download]]
    sha256 = "c63c910115cb21facd832d1c7151139cf4462fc187310ec3a01f243225164e0b"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.2+0/MQLib.v0.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
