[[MQLib]]
arch = "aarch64"
git-tree-sha1 = "72c206634c278c2bd629b3ef7381c9e67c31d10c"
os = "macos"

    [[MQLib.download]]
    sha256 = "17899613d0569cbe6af4dcd1346461b0c0f2add1f0f92679ef73c776728e794a"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.aarch64-apple-darwin.tar.gz"
[[MQLib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6a8420719fe138ccd342b2326f8de8d822882a7"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "99236be7c27323c86f00da3f71f5495539bb9dd4b09c773fe1602e746bf776d2"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a837887436ff56c6f651134190f4762a7b0d2cdc"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "b600ac4db365c7bcc12e9fd5aff75b0f6dc15e1880ddaee96f20eb6bc0ddb495"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[MQLib]]
arch = "aarch64"
git-tree-sha1 = "53e5981d1f1b814d0f4501e4e43d121799b049e6"
os = "freebsd"

    [[MQLib.download]]
    sha256 = "09f57c84dc16cd3840685b9d81d6c7826377f2009282793c9c7f2fe1e6988698"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.aarch64-unknown-freebsd.tar.gz"
[[MQLib]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "219a74ad196620fb6354003f6dbb1017f88a380a"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "46f546c79b8675aaa31dbd5594705333d94c076a741a3d1dcb59197055baf019"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MQLib]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2807300302eead73bf3e8a6c9ca11f96e21f221d"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "00b1174d0083748b1dcd49886eb402810f94c364045c648088a05f8152eaf58f"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MQLib]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b43908f22d1ddc8a5dba5e4dd3282aec3f745ad3"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "450a6f73e5d845c24b6bf78b79d82d80009eaf70f682086b57f34e1e93003db5"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MQLib]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fc1267473aa861890e2abd4533307acc43aaf09"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "c86e68e36d15ca3889ed8d1a6cc074859b0318987503d0f66e197588ed3da719"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MQLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57f04508fc9932b1588ad79d19ed97094ae9cefc"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "1f2e760d6adc5afa148cfeb791d111de4b4705b33ec6475e895bdf7b6e75037c"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.i686-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "054dfa38df4cb751cde9dc3007e8cd8e2bdddb12"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "a7a917a74457da05577b7d80464860c071b13bb0e0ec04eef2a872218d69c7d4"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.i686-linux-musl-cxx11.tar.gz"
[[MQLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acc65df12d5b78e0b259d17f4fef631dd04291db"
os = "windows"

    [[MQLib.download]]
    sha256 = "f3b90664b1785a2b0d651dfce3b6c691e748b9d0390a31d2611cf06a05aee26c"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[MQLib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd82eeeb0640c7a527d12f6cd4c1bedafb251aa6"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "c5c4a02af54d604943b40a85caf2166b7839d974c99406cc750e5473931ea3e9"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6177aabcbdafe0a1ca38e6fe0300f775f54f456e"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "b9ce8f7c95023241a437b046907eb1b0b51c1eecb1f8d57c46740171246c6773"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "x86_64"
git-tree-sha1 = "d4f7e1c00746b3b02748d432a74d8cd892908787"
os = "macos"

    [[MQLib.download]]
    sha256 = "2a362b66ce23957b83c1654161f41aaa6861294e3a6571b675a19258f3e712cb"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.x86_64-apple-darwin.tar.gz"
[[MQLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36bec407daa698166ac66b589c0bc0d5ea9399ef"
libc = "glibc"
os = "linux"

    [[MQLib.download]]
    sha256 = "609a7d9d7fc929cb429b5b7925f928ea4e87c3244e1049ef2352891955b53878"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MQLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7c18d06eb804c87eb98fa8c3910c2587fe11e1b"
libc = "musl"
os = "linux"

    [[MQLib.download]]
    sha256 = "440879709a98b56245f4445e62d0f1c5d65c284366e4dc61e70da951d38e6e1a"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[MQLib]]
arch = "x86_64"
git-tree-sha1 = "cefef7411d80ccf20517f7522e6c118da0252d9a"
os = "freebsd"

    [[MQLib.download]]
    sha256 = "a0b816e3bb3e12827464a5e94c430068feda7ccc2e1a494f65d36e66a5cf159e"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.x86_64-unknown-freebsd.tar.gz"
[[MQLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e8cb1635fb5e320239a1ccd8bbb9d8232b4f4e6"
os = "windows"

    [[MQLib.download]]
    sha256 = "5684ea633ad2b94bc5e5edc58f1d69b88d8e1ff1d98c6c1554c88f4f0f5119f8"
    url = "https://github.com/JuliaBinaryWrappers/MQLib_jll.jl/releases/download/MQLib-v0.1.1+0/MQLib.v0.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
