# Autogenerated wrapper script for MQLib_jll for i686-linux-gnu-cxx11
export MQLib, libmqlib_c_api

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("MQLib")
JLLWrappers.@declare_library_product(libmqlib_c_api, "libmqlib_c_api.so")
JLLWrappers.@declare_executable_product(MQLib)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmqlib_c_api,
        "lib/libmqlib_c_api.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        MQLib,
        "bin/MQLib",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
