# Autogenerated wrapper script for MQLib_jll for x86_64-w64-mingw32-cxx11
export MQLib, libmqlib_c_api

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("MQLib")
JLLWrappers.@declare_library_product(libmqlib_c_api, "libmqlib_c_api.dll")
JLLWrappers.@declare_executable_product(MQLib)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmqlib_c_api,
        "bin\\libmqlib_c_api.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        MQLib,
        "bin\\MQLib.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
