# Autogenerated wrapper script for MQLib_jll for x86_64-apple-darwin
export MQLib, libmqlib_c_api

JLLWrappers.@generate_wrapper_header("MQLib")
JLLWrappers.@declare_library_product(libmqlib_c_api, "@rpath/libmqlib_c_api.dylib")
JLLWrappers.@declare_executable_product(MQLib)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmqlib_c_api,
        "lib/libmqlib_c_api.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        MQLib,
        "bin/MQLib",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
