# Autogenerated wrapper script for MQLib_jll for x86_64-apple-darwin
export MQLib

JLLWrappers.@generate_wrapper_header("MQLib")
JLLWrappers.@declare_executable_product(MQLib)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        MQLib,
        "bin/MQLib",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
